version: 0.2
env: 
  variables: 
    DOTNET_FRAMEWORK: "4.6.2"
    PACKAGE_DIRECTORY: .\packages
    SOLUTION: .\JenkinsTestdemo.sln
phases: 
  build: 
    commands: 
      - "& \"C:\\ProgramData\\chocolatey\\bin\\NuGet.exe\" restore $env:SOLUTION PackagesDirectory $env:PACKAGE_DIRECTORY"
      - "& \"C:\\Program Files (x86)\\MSBuild\\14.0\\Bin\\MSBuild.exe\" p:FrameworkPathOverride=\"C:\\Program Files (x86)\\Reference Assemblies\\Microsoft\\Framework \\.NETFramework\\$env:DOTNET_FRAMEWORK\" $env:SOLUTION"
artifacts: 
  files: 
    - .\JenkinsTestdemo\bin\Debug\*
